update eks-with-spot to latest EKS version

diff --git a/tile/argocd-with-existing-eks/1.6.1x/tile-spec.yaml b/tile/argocd-with-existing-eks/1.6.1x/tile-spec.yaml
--- a/tile/argocd-with-existing-eks/1.6.1x/tile-spec.yaml
+++ b/tile/argocd-with-existing-eks/1.6.1x/tile-spec.yaml
@@ -63,6 +63,24 @@ spec:
           ARGOCD_SERVER=`kubectl get svc argocd-server -n argocd -o json  |jq -r '.status.loadBalancer.ingress[].hostname'`
           ARGOCD_BASE_URL=https://$ARGOCD_SERVER/argocd
           ARGOCD_TOKEN=`curl -s -k $ARGOCD_BASE_URL/api/v1/session -d $'{"username":"admin","password":"argocd-server-cf87b5c86-5xlv2"}'|jq -r '.token'`
+          if [ "$ARGOCD_TOKEN" = "" ]
+          then
+            
+            for i in {1..10}
+            do 
+              echo "REtry get TOKEN: $i"
+              ARGOCD_TOKEN=`curl -s -k $ARGOCD_BASE_URL/api/v1/session -d $'{"username":"admin","password":"argocd-server-cf87b5c86-5xlv2"}'|jq -r '.token'`
+              if [ "$ARGOCD_TOKEN" != "" ]
+              then
+                break
+              fi
+            done
+          fi
+          if [ "$ARGOCD_TOKEN" = "" ]
+          then
+            echo "!!!Fail to get ARGOCD_TOKEN!!!"
+            exit 1
+          fi
 
       - name: SetupRemoteCluster
         command: |
@@ -118,6 +136,10 @@ spec:
           sed -e 's/__github_repo__/'$githubRepo'/g' \
               -e 's/__github_access_token__/'$GITHUB_ACCESS_TOKEN'/g' ./add-repo.json > ./add-repo-go.json
           curl -s -k $ARGOCD_BASE_URL/api/v1/repositories -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@add-repo-go.json"
+      - name: ResetKube2Origin
+        command: |
+          # Reset kube context to origin
+          aws eks update-kubeconfig --name $(self.inputs.clusterName) --region $AWS_REGION --role-arn $(self.inputs.masterRoleARN) --kubeconfig $KUBECONFIG
         
           
   inputs:
@@ -160,7 +182,9 @@ spec:
     - name: appConfRepo
       inputType: String
       require: true
-
+    - name: appConfRepoBranch
+      inputType: String
+      require: true
 
   # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
   outputs:
diff --git a/tile/go-bumblebee-jazz/0.7.1x/tile-spec.yaml b/tile/go-bumblebee-jazz/0.7.1x/tile-spec.yaml
--- a/tile/go-bumblebee-jazz/0.7.1x/tile-spec.yaml
+++ b/tile/go-bumblebee-jazz/0.7.1x/tile-spec.yaml
@@ -30,7 +30,7 @@ spec:
       - name: PrepareAppContent
         command: |
           cd $TILE_HOME
-          rm -rf $APP_REPO;git clone https://github.com/$APP_CONF_REPO_USER/$APP_REPO.git
+          rm -rf $APP_REPO;git clone https://github.com/$APP_REPO_USER/$APP_REPO.git
           cd $APP_REPO
           git checkout $APP_REPO_BRANCH
           git pull
@@ -40,10 +40,10 @@ spec:
             cd manifests/kustomize/production/air
             sed -i -e 's/redis-cart:6379/'$prod_redis_endpoint'/g' air-deployment.yaml
           fi
-      - name: SyncAppContentToRepository
+      - name: SyncAppContentToConfigRepository
         command: |
           cd $TILE_HOME
-          rm -rf APP_CONF_REPO;git clone https://$APP_CONF_REPO_ACCESS_TOKEN:x-oauth-basic@github.com/$APP_CONF_REPO_USER/$APP_CONF_REPO.git
+          rm -rf $APP_CONF_REPO;git clone https://$APP_CONF_REPO_ACCESS_TOKEN:x-oauth-basic@github.com/$APP_CONF_REPO_USER/$APP_CONF_REPO.git
           cd $APP_CONF_REPO
           cp -r ../$APP_REPO/manifests/* .
           git add -A
@@ -68,7 +68,7 @@ spec:
       - name: Register2Codebuild
         command: |
           cd $TILE_HOME/scripts
-          ./import-source-credential.sh
+          ./import-source-credential.sh $APP_CONF_REPO_ACCESS_TOKEN $APP_CONF_REPO_USER
           ./create-iam-role.sh
           ./register-to-codebuild.sh
       - name: PrepareKubeConfig
@@ -84,6 +84,25 @@ spec:
         command: |
           cd $TILE_HOME/manifest/argocd
           ARGOCD_TOKEN=`curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/session -d $'{"username":"$(self.inputs.argocdUser)","password":"$(self.inputs.argocdPassword)"}'|jq -r '.token'`
+          if [ "$ARGOCD_TOKEN" = "" ]
+          then
+            
+            for i in {1..10}
+            do 
+              echo "REtry get TOKEN: $i"
+              ARGOCD_TOKEN=`curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/session -d $'{"username":"$(self.inputs.argocdUser)","password":"$(self.inputs.argocdPassword)"}'|jq -r '.token'`
+              if [ "$ARGOCD_TOKEN" != "" ]
+              then
+                break
+              fi
+            done
+          fi
+          if [ "$ARGOCD_TOKEN" = "" ]
+          then
+            echo "!!!Fail to get ARGOCD_TOKEN!!!"
+            exit 1
+          fi
+
           githubRepo=$(echo https://$APP_CONF_REPO_ACCESS_TOKEN:x-oauth-basic@github.com/$APP_CONF_REPO_USER/$APP_CONF_REPO.git | sed -e "s#/#\\\/#g")
 
           # add staging deployment 
